# Generated by Django 4.1.7 on 2023-11-19 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.UUIDField(auto_created=True, primary_key=True, serialize=False)),
                ('menu_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id_menu_item', models.UUIDField(auto_created=True, primary_key=True, serialize=False)),
                ('menu_item_name', models.CharField(max_length=50)),
                ('menu_item_cost', models.FloatField()),
                ('menu_item_price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='MenuItemCategory',
            fields=[
                ('id_menu_item_category', models.UUIDField(auto_created=True, primary_key=True, serialize=False)),
                ('menu_item_category', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='menu_item_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.menuitemcategory'),
        ),
        migrations.AddField(
            model_name='menu',
            name='menu_item',
            field=models.ManyToManyField(help_text='Seleccione los elementos del menu', to='restaurant.menuitem'),
        ),
    ]
