# Generated by Django 4.1.7 on 2023-11-19 17:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_menu_menuitem_menuitemcategory_delete_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitemcategory',
            name='id_menu_item_category',
            field=models.UUIDField(auto_created=True, default=uuid.UUID, primary_key=True, serialize=False),
        ),
    ]
