# Generated by Django 4.1.7 on 2023-11-19 17:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_alter_menuitemcategory_id_menu_item_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitemcategory',
            name='id_menu_item_category',
            field=models.UUIDField(auto_created=True, default=uuid.UUID('35bce849-e379-4d5c-af21-a47c5f17acfb'), primary_key=True, serialize=False),
        ),
    ]
