# Generated by Django 4.1.7 on 2023-11-19 17:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_alter_menuitemcategory_id_menu_item_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='id',
            field=models.UUIDField(auto_created=True, default=uuid.UUID('80790d80-c5bc-445a-b035-6b45d5afa702'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='id_menu_item',
            field=models.UUIDField(auto_created=True, default=uuid.UUID('7de985db-ba07-44e2-a952-2bf4ce913439'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='menuitemcategory',
            name='id_menu_item_category',
            field=models.UUIDField(auto_created=True, default=uuid.UUID('e01510cc-469f-4117-a7a0-d02d0de5d4bd'), primary_key=True, serialize=False),
        ),
    ]
