# Generated by Django 4.1.7 on 2023-11-19 17:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_alter_menu_id_alter_menuitem_id_menu_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='id_menu_item',
            field=models.UUIDField(auto_created=True, default=uuid.UUID('351b6659-8b70-45a9-a99f-c0396c8e1876'), primary_key=True, serialize=False),
        ),
    ]
