# Generated by Django 4.1.7 on 2023-11-19 17:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_alter_menuitem_id_menu_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='id_menu_item',
            field=models.UUIDField(auto_created=True, default=uuid.UUID('ba1153eb-c43b-479b-bad4-898f96e9066a'), primary_key=True, serialize=False),
        ),
    ]
