# Generated by Django 4.1.7 on 2023-11-19 19:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0009_alter_menu_id_alter_menuitem_id_menu_item_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id_ingrediente', models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('ingrediente_name', models.CharField(max_length=50, unique=True)),
                ('ingrediente_cost', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('id_unidad_medida', models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('unidad_medida', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='IngredienteExistencia',
            fields=[
                ('id_ingrediente_existencia', models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('cantidad', models.FloatField()),
                ('ingrediente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.ingrediente')),
                ('unidad_medida', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.unidadmedida')),
            ],
        ),
        migrations.CreateModel(
            name='IngredienteDetalle',
            fields=[
                ('id_ingrediente_detalles', models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('cantidad', models.FloatField()),
                ('ingrediente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.ingrediente')),
                ('unidad_medida', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.unidadmedida')),
            ],
        ),
    ]
