# Generated by Django 4.1.7 on 2023-11-19 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0010_ingrediente_unidadmedida_ingredienteexistencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='ingredientes',
            field=models.ManyToManyField(to='restaurant.ingredientedetalle'),
        ),
    ]
