# Generated by Django 4.1.7 on 2023-11-19 20:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0011_menuitem_ingredientes'),
    ]

    operations = [
        migrations.CreateModel(
            name='MesaStatus',
            fields=[
                ('id_mesa_status', models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('mesa_status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MesaUbicacion',
            fields=[
                ('id_mesa_ubicacion', models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('mesa_ubicacion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id_mesa', models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('nombre_mesa', models.CharField(max_length=50)),
                ('mesa_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.mesastatus')),
                ('mesa_ubicacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.mesaubicacion')),
            ],
        ),
    ]
