# Generated by Django 4.1.7 on 2023-11-19 21:37

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0012_mesastatus_mesaubicacion_mesa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id_orden', models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('fecha_orden', models.DateTimeField(default=datetime.datetime.today)),
                ('mesa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.mesa')),
            ],
        ),
        migrations.CreateModel(
            name='OrdenStatus',
            fields=[
                ('id_orden_status', models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('orden_status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='OrdenDetalle',
            fields=[
                ('id_orden_detalle', models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('costo_menu_item_al_momento_de_la_venta', models.FloatField()),
                ('precio_menu_item_al_momento_de_la_venta', models.FloatField()),
                ('menu_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.menuitem')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.orden')),
            ],
        ),
        migrations.AddField(
            model_name='orden',
            name='orden_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.ordenstatus'),
        ),
    ]
