# Generated by Django 4.1.7 on 2023-11-19 23:04

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('restaurant', '0014_metodopago_metodopagodetalle_venta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to=settings.AUTH_USER_MODEL)),
                ('id_cliente', models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('nombre_cliente', models.CharField(max_length=50)),
                ('numero_telefono', models.CharField(max_length=8, null=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Mesero',
            fields=[
                ('id_mesero', models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('nombre_mesero', models.CharField(max_length=50)),
                ('numero_telefono', models.CharField(max_length=8, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='orden',
            name='cliente',
            field=models.ManyToManyField(to='restaurant.cliente'),
        ),
        migrations.AddField(
            model_name='orden',
            name='mesero',
            field=models.ManyToManyField(to='restaurant.mesero'),
        ),
    ]
