# Generated by Django 4.1.7 on 2023-11-19 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0015_cliente_mesero_orden_cliente_orden_mesero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='menu_item',
            field=models.ManyToManyField(help_text='Seleccione los elementos del menu', null=True, to='restaurant.menuitem'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='ingredientes',
            field=models.ManyToManyField(null=True, to='restaurant.ingredientedetalle'),
        ),
        migrations.AlterField(
            model_name='orden',
            name='cliente',
            field=models.ManyToManyField(null=True, to='restaurant.cliente'),
        ),
        migrations.AlterField(
            model_name='orden',
            name='mesero',
            field=models.ManyToManyField(null=True, to='restaurant.mesero'),
        ),
    ]
