# Generated by Django 4.1.7 on 2023-11-19 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0016_alter_menu_menu_item_alter_menuitem_ingredientes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='menu_item',
            field=models.ManyToManyField(blank=True, help_text='Seleccione los elementos del menu', to='restaurant.menuitem'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='ingredientes',
            field=models.ManyToManyField(blank=True, to='restaurant.ingredientedetalle'),
        ),
        migrations.AlterField(
            model_name='orden',
            name='cliente',
            field=models.ManyToManyField(blank=True, to='restaurant.cliente'),
        ),
        migrations.AlterField(
            model_name='orden',
            name='mesero',
            field=models.ManyToManyField(blank=True, to='restaurant.mesero'),
        ),
    ]
